config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :reports do
    resources :comments, only: [:create, :edit, :update, :destroy], module: :reports
  end

  resources :books do
    resources :comments, only: [:create, :edit, :update, :destroy], module: :books
  end

  resources :users, only: [:show, :index, :edit, :update]
  resources :users do
    resources :followings, only: [:index], controller: "users/followings"
    resources :followers, only: [:index], controller: "users/followers"
  end
  resources :relationships, only: [:create, :destroy]
  root to: "books#index"
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,  :validatable, :omniauthable, omniauth_providers: %i(github)
  validates :user_name, presence: true, length: { maximum: 30 }
  validates :self_introduction, length: { maximum: 200 }
  has_and_belongs_to_many :books
  has_one_attached :avatar
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :reports, dependent: :destroy
  has_many :comments, dependent: :destroy

  def self.find_for_github_oauth(auth, signed_in_resource = nil)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.user_name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/followers_controller.rb
# frozen_string_literal: true

class Users::FollowersController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @user  = User.find(params[:user_id])
    @users = @user.followers
  end
end

app/controllers/users/followings_controller.rb
# frozen_string_literal: true

class Users::FollowingsController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @user  = User.find(params[:user_id])
    @users = @user.following
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.find_for_github_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "GitHub") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def build_resource(hash = {})
    hash[:uid] = User.create_unique_string
    super
  end

  protected
    def after_update_path_for
      user_path(id: current_user.id)
    end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :set_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @following_count = @user.following.count
    @followers_count = @user.followers.count
  end

  def index
    @users = User.all
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user)
    else
      redirect_to edit_user_path(current_user)
    end
  end

  private
    def set_user
      @user = current_user
    end

    def user_params
      params.fetch(:user, {}).permit(:user_name, :email, :postal_code, :address, :self_introduction, :avatar)
    end
end

app/views/users/_following_button.html.erb
<%= form_with model: current_user.active_relationships.build do |f| %>
  <div><%= hidden_field_tag :followed_id, user_id %></div>
  <%= f.submit t("relationship.follow") %>
<% end %>

app/views/users/_unfollow_button.html.erb
<%= form_with model: current_user.active_relationships.find_by(followed_id: user_id),
            html: { method: :delete } do |f| %>
  <%= f.submit t("relationship.unfollow") %>
<% end %>

app/views/users/edit.html.erb
<h1><%= t("users.update.title") %></h1>

<%= form_with model: @user do |form| %>
  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, max_length: "200", size: "40x5" %>
  </div>

  <div class="field">
    <%= form.label :self_introduction %>
    <%= form.text_area :self_introduction, max_length: "200", size: "40x5" %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to t("links.top"), root_path %>

app/views/users/index.html.erb
<h1><%= t("users.index.title") %></h1>
<table>
  <thead>
    <tr>
      <th><%= User.human_attribute_name(:user_name) %></th>
      <th><%= User.human_attribute_name(:self_introduction) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <% next if current_user.id == user.id %>
        <td><%= link_to user.user_name, user_path(user.id) %></td>
        <td><%= user.self_introduction %></td>
        <% if current_user.following?(user) %>
          <td> 
            <%= render partial: "unfollow_button", locals: {user_id: user.id} %>
          </td>
        <% else %>
          <td> 
            <%= render partial: "following_button", locals: {user_id: user.id} %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t("links.top"), root_path %>

app/views/users/show.html.erb
<h1><%= t("users.show.title") %></h1>
<% if @user.avatar.attached? %>
  <%= image_tag(@user.avatar.variant(resize_to_fill: [150, 150])) %>
<% end %>

<p>
  <%= link_to "#{@following_count}フォロー中", user_followings_path(@user.id) %>
  <%= link_to "#{@followers_count}フォロワー", user_followers_path(@user.id) %>
</p>

<% if @user.id == current_user.id %>
  <%= link_to t("users.update.title"), edit_user_path %>
<% elsif current_user.following?(@user) %>
  <%= render partial: "unfollow_button", locals: {user_id: @user.id} %>
<% else %>
  <%= render partial: "following_button", locals: {user_id: @user.id} %>
<% end %>
<p>
  <strong><%= User.human_attribute_name(:user_name) + ":" %></strong>
  <%= @user.user_name %>
</p>
<p>
  <strong><%= User.human_attribute_name(:email) + ":" %></strong>
  <%= @user.email %>
</p>
<p>
  <strong><%= User.human_attribute_name(:postal_code) + ":" %></strong>
  <%= @user.postal_code %>
</p>
<p>
  <strong><%= User.human_attribute_name(:address) + ":" %></strong>
  <%= @user.address %>
</p>
<p>
  <strong><%= User.human_attribute_name(:self_introduction) + ":" %></strong>
  <%= @user.self_introduction %>
</p>

<%= link_to t("links.top"), root_path %>

app/views/users/show_follow.html.erb
<h1><%= "#{@user.user_name}の#{@title}" %></h1>

<table>
  <thead>
    <tr>
      <th><%= User.human_attribute_name(:user_name) %></th>
      <th><%= User.human_attribute_name(:self_introduction) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.user_name, user_path(user.id) %></td>
        <td><%= user.self_introduction %></td>
        <% if current_user.following?(user) %>
          <td> 
            <%= render partial: "unfollow_button", locals: {user_id: user.id} %>
          </td>
        <% else %>
          <td> 
            <%= render partial: "following_button", locals: {user_id: user.id} %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t("links.top"), root_path %>
<%= link_to t("links.back"), user_path(@user.id) %>