config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :reports do
    resources :comments, only: [:create, :edit, :update, :destroy], module: :reports
  end

  resources :books do
    resources :comments, only: [:create, :edit, :update, :destroy], module: :books
  end

  resources :users, only: [:show, :index, :edit, :update]
  resources :users do
    resources :followings, only: [:index], controller: "users/followings"
    resources :followers, only: [:index], controller: "users/followers"
  end
  resources :relationships, only: [:create, :destroy]
  root to: "books#index"
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  include Commentable
  mount_uploader :picture, PictureUploader
  paginates_per 5
  has_and_belongs_to_many :users
end

app/controllers/books/comments_controller.rb
# frozen_string_literal: true

class Books::CommentsController < CommentsController
  before_action :set_commentable

  private
    def set_commentable
      @commentable = Book.find(params[:book_id])
    end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_current_user_book, only: [:edit, :update, :destroy]

  # GET /books
  def index
    @books = Book.order(:title).page(params[:page])
  end

  # GET /books/1
  def show
    @book = Book.find(params[:id])
    @user_id = @book.users.first.id
  end

  # GET /books/new
  def new
    @book = current_user.books.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  def create
    @book = current_user.books.build(book_params)

    if @book.save
      current_user.books << @book
      redirect_to @book, notice: t("books.created.notice")
    else
      render :new
    end
  end

  # PATCH/PUT /books/1
  def update
    if @book.update(book_params)
      redirect_to @book, notice: t("books.updated.notice")
    else
      render :edit
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy
    redirect_to books_url, notice: t("books.deleted.notice")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_current_user_book
      @book = current_user.books.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :memo, :author, :picture)
    end
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_area :author %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1><%= t("books.update.title") %></h1>

<%= render 'form', book: @book %>

<%= link_to t("links.show"), @book %> |
<%= link_to t("links.back"), books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t("books.index.title") %></h1>
<%= page_entries_info @books, entry_name: Book.model_name.human %>
<%= paginate @books %>
<table>
  <thead>
    <tr>
      <th><%= User.human_attribute_name(:user_name) %></th>
      <th><%= Book.human_attribute_name(:title) %></th>
      <th><%= Book.human_attribute_name(:memo) %></th>
      <th><%= Book.human_attribute_name(:author) %></th>
      <th><%= Book.human_attribute_name(:picture) %></th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <% if book.users.first&.id  %>
            <%= link_to book.users.first&.user_name, user_path(book.users.first&.id) %>
          <% end %>
        </td>
        <td><%= book.title %></td>
        <td><%= book.memo %></td>
        <td><%= book.author %></td>
        <td><%= book.picture %></td>
        <td><%= link_to t("links.show"), book %></td>
        <% if book.users.first&.id == current_user.id  %>
          <td><%= link_to t("links.edit"), edit_book_path(book) %></td>
          <td><%= link_to t("links.delete"), book, method: :delete, data: { confirm: t("books.delete.confirm") } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t("books.create.title"), new_book_path %>
<%= link_to t("reports.index.title"), reports_path %>
<%= link_to t("links.profile"), user_path(current_user.id) %>
<%= link_to t("links.user_list"), users_path %>
<%= link_to t("links.logout"), destroy_user_session_path, method: :delete %>

app/views/books/new.html.erb
<h1><%= t("books.create.title") %></h1>

<%= render 'form', book: @book %>

<%= link_to t("links.back"), books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Book.human_attribute_name(:title) + ":" %></strong>
  <%= @book.title %>
</p>

<p>
  <strong><%= Book.human_attribute_name(:memo) + ":" %></strong>
  <%= @book.memo %>
</p>

<p>
  <strong><%= Book.human_attribute_name(:author) + ":" %></strong>
  <%= @book.author %>
</p>

<p>
  <strong><%= Book.human_attribute_name(:picture) + ":" %></strong>
  <%= image_tag(@book.picture_url) if @book.picture.present? %>
</p>

<% if @user_id == current_user.id %>
  <%= link_to t("links.edit"), edit_book_path(@book) %>
  <%= link_to t("links.delete"), @book, method: :delete, data: { confirm: t("books.delete.confirm") } %>
<% end %>

<h3><%= t("comments.index.title") %></h3>
<table>
  <thead>
    <tr>
      <th><%= User.human_attribute_name(:user_name) %></th>
      <th><%= Comment.human_attribute_name(:body) %></th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% @book.comments.each do |comment| %>
      <tr class="comment">
        <td><%= comment.user.user_name %></td>
        <td><%= comment.body %></td>
        <% if comment.user == current_user %>
          <td><%= link_to t("links.edit"), [:edit, comment.commentable, comment] %></td>
          <td><%= link_to t("links.delete"), [comment.commentable, comment], method: :delete, data: { confirm: t("comments.delete.confirm") } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render partial: "comments/form", locals: { commentable: @book, comment: @book.comments.new } %>

<%= link_to t("links.back"), books_path %>