config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :reports do
    resources :comments, only: [:create, :edit, :update, :destroy], module: :reports
  end

  resources :books do
    resources :comments, only: [:create, :edit, :update, :destroy], module: :books
  end

  resources :users, only: [:show, :index, :edit, :update]
  resources :users do
    resources :followings, only: [:index], controller: "users/followings"
    resources :followers, only: [:index], controller: "users/followers"
  end
  resources :relationships, only: [:create, :destroy]
  root to: "books#index"
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  include Commentable

  belongs_to :user
end

app/controllers/reports/comments_controller.rb
# frozen_string_literal: true

class Reports::CommentsController < CommentsController
  before_action :set_commentable

  private
    def set_commentable
      @commentable = Report.find(params[:report_id])
    end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_current_user_report, only: [:edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])
    @user_id = @report.user_id
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = current_user.reports.build(report_params)

    if @report.save
      redirect_to @report, notice: t("reports.created.notice")
    else
      render :new
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    if @report.update(report_params)
      redirect_to @report, notice: t("reports.updated.notice")
    else
      render :edit
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    redirect_to reports_url, notice: t("reports.deleted.notice")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_current_user_report
      @report = current_user.reports.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.require(:report).permit(:title, :content)
    end
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1><%= t("reports.update.title") %></h1>

<%= render 'form', report: @report %>

<%= link_to t("links.show"), @report %> |
<%= link_to t("links.back"), reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t("reports.index.title") %></h1>

<table>
  <thead>
    <tr>
      <th><%= User.human_attribute_name(:user_name) %></th>
      <th><%= Report.human_attribute_name(:title) %></th>
      <th><%= Report.human_attribute_name(:content) %></th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= link_to report.user.user_name, user_path(report.user_id) %></td>
        <td><%= report.title %></td>
        <td><%= report.content %></td>
        <td><%= link_to t("links.show"), report %></td>
        <% if report.user_id == current_user.id  %>
          <td><%= link_to t("links.edit"), edit_report_path(report) %></td>
          <td><%= link_to t("links.delete"), report, method: :delete, data: { confirm: t("reports.delete.confirm") } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t("books.index.title"), books_path %>
<%= link_to t("reports.create.title"), new_report_path %>
<%= link_to t("links.profile"), user_path(current_user.id) %>
<%= link_to t("links.user_list"), users_path %>
<%= link_to t("links.logout"), destroy_user_session_path, method: :delete %>

app/views/reports/new.html.erb
<h1><%= t("reports.create.title") %></h1>

<%= render 'form', report: @report %>

<%= link_to t("links.back"), reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Report.human_attribute_name(:title) + ":" %></strong>
  <%= @report.title %>
</p>

<p>
  <strong><%= Report.human_attribute_name(:content) + ":" %></strong>
  <%= @report.content %>
</p>

<% if @user_id == current_user.id %>
  <%= link_to t("links.edit"), edit_report_path(@report) %>
  <%= link_to t("links.delete"), @report, method: :delete, data: { confirm: t("reports.delete.confirm") } %>
<% end %>

<h3><%= t("comments.index.title") %></h3>
<table>
  <thead>
    <tr>
      <th><%= User.human_attribute_name(:user_name) %></th>
      <th><%= Comment.human_attribute_name(:body) %></th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% @report.comments.each do |comment| %>
      <tr class="comment">
        <td><%= comment.user.user_name %></td>
        <td><%= comment.body %></td>
        <% if comment.user == current_user %>
          <td><%= link_to t("links.edit"), [:edit, comment.commentable, comment] %></td>
          <td><%= link_to t("links.delete"), [comment.commentable, comment], method: :delete, data: { confirm: t("comments.delete.confirm") } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render partial: "comments/form", locals: { commentable: @report, comment: @report.comments.new } %>

<%= link_to t("links.back"), reports_path %>